---
- name: Envio de correo
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: sending an e-mail using Gmail SMTP servers
      command: "ansible-playbook send_gmail.yml"
        
